### ISSUE TITLE
👩‍💻Progress

### ISSUE THREAD

**Issue by rohjs** [whroh/portfolio-2019#2]
# Progress

## Tasks

- [ ] **Configure project**
  - [ ] Install `package.json`
  - [ ] Create `.prettierrc`
  - [ ] Customize `next.config.js`
  - [ ] Create a layout component: `<DefaultLayout />`
  - [ ] Create a dummy `<IndexPage />`
